Repository DedSecInside/Awesome-Scripts, pull requests merged in 2018-10, with the labels that each got.

#1 SystemDetails
  system.py
Labels: enhancement

#2 Face Detection
  face_detect.py
Labels: enhancement

#4 Face Detect
  haarcascade_frontalface_default.xml
Labels: HACKTOBERFEST, enhancement

#5 Index
  README.md
Labels: HACKTOBERFEST, enhancement

#9 Added gmail api testing script
  Gmail_API_script/README.md
  Gmail_API_script/credentials.json
  Gmail_API_script/main.py
Labels: HACKTOBERFEST, enhancement

#8 added new script for simple crc usage
  crc_check.py
Labels: HACKTOBERFEST, enhancement

#7 Create proxy_request.py
  proxy_request.py
Labels: HACKTOBERFEST, enhancement

#6 add keylogger script
  keylogger.py
Labels: HACKTOBERFEST, enhancement

#10 Create 10print.py
  Misc/10print.py
Labels: HACKTOBERFEST, enhancement

#15 Add Python script for message sending via textbelt
  Misc/Auto-Message-Sender/README.md
  Misc/Auto-Message-Sender/main.py
Labels: HACKTOBERFEST, enhancement

#12 Added twiiter api script
  twitter_api/README.md
  twitter_api/main.py
Labels: HACKTOBERFEST, enhancement

#19 Add Discord API script in JavaScript.
  Discord API/ping.js
  Discord API/readme.md
Labels: HACKTOBERFEST, enhancement

#24 Added Python script to get data from RSS Feed URL
  Misc/GetDataFromRssUrl.py
Labels: HACKTOBERFEST, enhancement

#25 KNN algorithm
  Machine Learning & AI/KNN_with_scikit_learn.py
  Machine Learning & AI/KNN_without_scikit_learn.py
Labels: HACKTOBERFEST, enhancement

#30 Sorting files and folders in a directory
  Misc/sorted_files.py
Labels: HACKTOBERFEST, enhancement

#29 added weather api
  APIs/weather_api/weather_api.py
Labels: HACKTOBERFEST, enhancement

#32 Add files via upload
  Misc/cricbuzz_scrap.py
Labels: HACKTOBERFEST, enhancement

#33 Create wxchallenge_usl.py
  Misc/wxchallenge_usl.py
Labels: HACKTOBERFEST, enhancement

#34 Added worklog generator
  Misc/Work_Log_Generator/README.rst
  Misc/Work_Log_Generator/requirements.txt
  Misc/Work_Log_Generator/resources/icone.ico
  Misc/Work_Log_Generator/resources/loader.gif
  Misc/Work_Log_Generator/resources/save.png
  Misc/Work_Log_Generator/work_log.py
Labels: HACKTOBERFEST, enhancement

#36 Issue#35 updated the readme file with list of scripts
  README.md
Labels: HACKTOBERFEST, enhancement, good first issue

#39 Added svm implemented with scikit learn
  Machine Learning & AI/svm_with_scikit_learn.py
Labels: HACKTOBERFEST, enhancement

#41 Create shell.py
  Security & Privacy/shell.py
Labels: HACKTOBERFEST, enhancement

#45 Fix file name of Misc/Directory-organiser.py
  Misc/Directory-organiser.py
  README.md
Labels: HACKTOBERFEST, good first issue

#43 Add life-calendar.rb
  Misc/life-calendar.rb
Labels: HACKTOBERFEST, good first issue

#44 Add Get Location Info to Misc
  Misc/Get_Location_Info/README.md
  Misc/Get_Location_Info/__init__.py
  Misc/Get_Location_Info/requirements.txt
  Misc/Get_Location_Info/script.py
Labels: HACKTOBERFEST, enhancement, good first issue

#46 Add a script to simulate a verbose mode for 'git gc'
  Misc/git-gcv
  README.md
Labels: HACKTOBERFEST, enhancement, good first issue
